### ISSUE TITLE
New Ontoportal website

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal/ontoportal-project#21]
## Context 
See https://github.com/ontoportal/ontoportal-project/discussions/9

## Goal

Move the current ontoportal website (https://ontoportal.org/) to GitHub page-based one, harmonizing with the new documentation and opening it to open contributions.

Currently, it's available here: https://ontoportal.github.io/website

### Requirements 

- [x] Using this template https://jekyllthemes.io/theme/hydra-jekyll-theme
- [x] Update website brand color to the ontoportal one(https://github.com/ontoportal/website/commit/ea65f69caedf509bf21eb4513e326960d5b24435)
- [x] Update the about page to be the Alliance about (https://github.com/ontoportal/website/commit/6f80ac200e18b6e2fbed02dcd93292a476e37ce7)
- [x] Add a Twitter section and update the home page content  (https://github.com/ontoportal/website/commit/030494f4111f01270075cc6171d3cef9cd07dbad)
- [x] Migrate the current posts/pages (https://github.com/ontoportal/website/pull/2)
- [x] Add a configurable alliance members section (https://github.com/ontoportal/website/commit/1f445491a6f81cd0473b421f720e2abb8441c197)
- [x] Add a confiugrable sponsons section (https://github.com/ontoportal/website/pull/3)
- [x] Add a link to Ontoportal documentation  (https://github.com/ontoportal/website/commit/ef8f230e739f9687001607da98690a19f0e146b1)
- [x] Add a link to Connect to Ontoportal GitHub (https://github.com/ontoportal/website/commit/ef8f230e739f9687001607da98690a19f0e146b1)
- [x] Finalise the website content (the terms to use, the sponsors to add,...)
- [x] Do DNS redirect from https://ontoportal.github.io/website/ to https://ontoportal.org/

**Comment by alexskr** [comment]
site is live

**Comment by jvendetti** [comment]
The site footer has 3 visible "Contact us" links. I assume the intention here was to have just one?

<img width="1023" alt="Screen Shot 2023-05-16 at 11 33 18 AM" src="https://github.com/ontoportal/ontoportal-project/assets/1696923/b0743f95-e0bb-4514-b156-2d2d76f5b23b">

**Comment by jonquet** [comment]
Yes I have not found yet (quickly the solution for this).
I also need to fix the testimonials.

**Comment by syphax-bouazzouni** [comment]
> The site footer has 3 visible "Contact us" links. I assume the intention here was to have just one?
> 
> <img alt="Screen Shot 2023-05-16 at 11 33 18 AM" width="1023" src="https://user-images.githubusercontent.com/1696923/238739794-b0743f95-e0bb-4514-b156-2d2d76f5b23b.png">

The contact us issue is fixed with https://github.com/ontoportal/website/pull/7 (at the same time I added the GitHub icon in the footer also)




> site is live

Thanks, @alexskr for the DNS redirection.


> Yes I have not found yet (quickly the solution for this). I also need to fix the testimonials.

Indeed it was not obvious, but thanks for all the content that you have added. It did change a lot (in a good way) since the last time that saw it.

**Comment by syphax-bouazzouni** [comment]
I close since all the requirements are fulfilled and  bugs resolved 

Please @jonquet and @graybeal, reopen if needed to add something.
