### ISSUE TITLE
Troubleshooting large ontologies section is missing in the help - https://ontoportal.github.io/documentation/administration/ontologies/troubleshooting_submissions/#troubleshooting-very-large-ontologies

### ISSUE THREAD

**Issue by chris-day** [ontoportal/ontoportal-project#25]
**Describe the bug**
The link in the help to https://ontoportal.github.io/documentation/administration/ontologies/troubleshooting_submissions/#troubleshooting-very-large-ontologies

is dead.

**To Reproduce**
1. Go to 'https://ontoportal.github.io/documentation/administration/ontologies/ontology_limitations'
2. Click on 'Troubleshooting Submissions' hyperlink
4.  See error

**Expected behavior**
The correct page to help troubleshooting submission of large ontologies

**Comment by syphax-bouazzouni** [comment]
@chris-day thanks for the bug report.
It is resolved now, thanks to https://github.com/ontoportal/documentation/pull/35
